name: Super-Linter

on: push

jobs:
  super-lint: 
    name: biraluu code
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v3

        env:
        
          DEFAULT_BRANCH: main
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
